//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitsmith {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitsmith.JsonSchemas", typeof(JsonSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-06/schema#&quot;,
        ///    &quot;$ref&quot;: &quot;#/definitions/Welcome&quot;,
        ///    &quot;definitions&quot;: {
        ///        &quot;Citation&quot;: {
        ///            &quot;type&quot;: &quot;object&quot;,
        ///            &quot;additionalProperties&quot;: false,
        ///            &quot;properties&quot;: {
        ///                &quot;Author&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;Source&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;Location&quot;: {
        ///                    &quot;type&quot;: &quot;integer&quot;
        ///                },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schemas_citation_json {
            get {
                return ResourceManager.GetString("schemas_citation_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-06/schema#&quot;,
        ///    &quot;$ref&quot;: &quot;#/definitions/Welcome&quot;,
        ///    &quot;definitions&quot;: {
        ///        &quot;Contact&quot;: {
        ///            &quot;type&quot;: &quot;object&quot;,
        ///            &quot;additionalProperties&quot;: false,
        ///            &quot;properties&quot;: {
        ///                &quot;LastName&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;FirstName&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;Email&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schemas_contact_json {
            get {
                return ResourceManager.GetString("schemas_contact_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-06/schema#&quot;,
        ///    &quot;$ref&quot;: &quot;#/definitions/Welcome&quot;,
        ///    &quot;definitions&quot;: {
        ///        &quot;Person&quot;: {
        ///            &quot;type&quot;: &quot;object&quot;,
        ///            &quot;additionalProperties&quot;: false,
        ///            &quot;properties&quot;: {
        ///                &quot;Name&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;Email&quot;: {
        ///                    &quot;type&quot;: &quot;string&quot;
        ///                },
        ///                &quot;Age&quot;: {
        ///                    &quot;type&quot;: &quot;integer&quot;
        ///                }
        ///            },
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schemas_person_json {
            get {
                return ResourceManager.GetString("schemas_person_json", resourceCulture);
            }
        }
    }
}
