//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitsmith {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitsmith.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///  
        ///  &lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; /&gt;
        ///  &lt;State name=&quot;Authenticate&quot; display=&quot;Authenticate&quot; /&gt;
        ///  &lt;State name=&quot;Unauthorized&quot; display=&quot;Unauthorized&quot; /&gt;
        ///  &lt;State name=&quot;Error&quot; display=&quot;Error&quot; /&gt;
        ///  &lt;State name=&quot;Startup&quot; display=&quot;Startup&quot; /&gt;
        ///  &lt;State name=&quot;Dashboard&quot; display=&quot;Dashboard&quot; /&gt;
        ///  &lt;State [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nav_state_machine {
            get {
                return ResourceManager.GetString("nav_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///  &lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; /&gt;
        ///  &lt;State name=&quot;Authenticated&quot; display=&quot;Authenticated&quot; /&gt;
        ///  &lt;State name=&quot;Content&quot; display=&quot;Content&quot; /&gt;
        ///
        ///  &lt;Transition name=&quot;Login&quot; origin=&quot;LoggedOff&quot; destination=&quot;Authenticated&quot; order=&quot;0&quot; /&gt;
        ///  &lt;Transition name=&quot;Content&quot; origin=&quot;Authenticated&quot; destination=&quot;Con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string simple_state_machine {
            get {
                return ResourceManager.GetString("simple_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///	&lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; /&gt;
        ///	&lt;State name=&quot;Authenticated&quot; display=&quot;Authenticated&quot; /&gt;
        ///	&lt;State name=&quot;Authorized&quot; display=&quot;Authorized&quot; /&gt;
        ///	&lt;State name=&quot;Unauthorized&quot; display=&quot;Unauthorized&quot; /&gt;
        ///	&lt;State name=&quot;Error&quot; display=&quot;Error&quot; /&gt;
        ///	&lt;State name=&quot;Administration&quot; display=&quot;Admin&quot;/&gt;
        ///	&lt;State nam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string statemachine {
            get {
                return ResourceManager.GetString("statemachine", resourceCulture);
            }
        }
    }
}
