//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitsmith {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitsmith.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///an
        ///the
        ///it
        ///when
        ///where.
        /// </summary>
        public static string indexer_exclusions {
            get {
                return ResourceManager.GetString("indexer_exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen|1|1| In the beginning God created the heaven and the earth.~
        ///Gen|1|2| And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.~
        ///Gen|1|3| And God said, Let there be light: and there was light.~
        ///Gen|1|4| And God saw the light, that it was good: and God divided the light from the darkness.~
        ///Gen|1|5| And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.~
        ///Ge [rest of string was truncated]&quot;;.
        /// </summary>
        public static string kjvdat {
            get {
                return ResourceManager.GetString("kjvdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///  
        ///  &lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; /&gt;
        ///  &lt;State name=&quot;Authenticate&quot; display=&quot;Authenticate&quot; /&gt;
        ///  &lt;State name=&quot;Unauthorized&quot; display=&quot;Unauthorized&quot; /&gt;
        ///  &lt;State name=&quot;Error&quot; display=&quot;Error&quot; /&gt;
        ///  &lt;State name=&quot;Startup&quot; display=&quot;Startup&quot; /&gt;
        ///  &lt;State name=&quot;Dashboard&quot; display=&quot;Dashboard&quot; /&gt;
        ///  &lt;State [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nav_state_machine {
            get {
                return ResourceManager.GetString("nav_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///  &lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; isNavigate=&quot;true&quot; order=&quot;9&quot; /&gt;
        ///  &lt;State name=&quot;Authenticated&quot; display=&quot;Authenticated&quot; /&gt;
        ///  &lt;State name=&quot;Content&quot; display=&quot;Content&quot; isNavigate=&quot;true&quot; order=&quot;0&quot; /&gt;
        ///  &lt;State name=&quot;Tasks&quot; display=&quot;Tasks&quot; isNavigate=&quot;true&quot; order=&quot;1&quot; /&gt;
        ///  &lt;State name=&quot;TimeEntry&quot; displa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string simple_state_machine {
            get {
                return ResourceManager.GetString("simple_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StateMachine xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; beginState=&quot;LoggedOff&quot; endState=&quot;LoggedOff&quot;&gt;
        ///	&lt;State name=&quot;LoggedOff&quot; display=&quot;LoggedOff&quot; /&gt;
        ///	&lt;State name=&quot;Authenticated&quot; display=&quot;Authenticated&quot; /&gt;
        ///	&lt;State name=&quot;Authorized&quot; display=&quot;Authorized&quot; /&gt;
        ///	&lt;State name=&quot;Unauthorized&quot; display=&quot;Unauthorized&quot; /&gt;
        ///	&lt;State name=&quot;Error&quot; display=&quot;Error&quot; /&gt;
        ///	&lt;State name=&quot;Administration&quot; display=&quot;Admin&quot;/&gt;
        ///	&lt;State nam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string statemachine {
            get {
                return ResourceManager.GetString("statemachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,able,about,across,after,all,almost,also,am,among,an,and,any,are,as,at,be,because,been,but,by,can,cannot,could,dear,did,do,does,either,else,ever,every,for,from,get,got,had,has,have,he,her,hers,him,his,how,however,i,if,in,into,is,it,its,just,least,let,like,likely,may,me,might,most,must,my,neither,no,nor,not,of,off,often,on,only,or,other,our,own,rather,said,say,says,she,should,since,so,some,than,that,the,their,them,then,there,these,they,this,tis,to,too,twas,us,wants,was,we,were,what,when,where,which,while,wh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_english {
            get {
                return ResourceManager.GetString("stop_words_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,abord,absolument,afin,ah,ai,aie,aient,aies,ailleurs,ainsi,ait,allaient,allo,allons,allô,alors,anterieur,anterieure,anterieures,apres,après,as,assez,attendu,au,aucun,aucune,aucuns,aujourd,aujourd&apos;hui,aupres,auquel,aura,aurai,auraient,aurais,aurait,auras,aurez,auriez,aurions,aurons,auront,aussi,autant,autre,autrefois,autrement,autres,autrui,aux,auxquelles,auxquels,avaient,avais,avait,avant,avec,avez,aviez,avions,avoir,avons,ayant,ayez,ayons,b,bah,bas,basee,bat,beau,beaucoup,bien,bigre,bon,boum,bravo,brrr,c, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_french {
            get {
                return ResourceManager.GetString("stop_words_french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,ab,aber,ach,acht,achte,achten,achter,achtes,ag,alle,allein,allem,allen,aller,allerdings,alles,allgemeinen,als,also,am,an,ander,andere,anderem,anderen,anderer,anderes,anderm,andern,anderr,anders,au,auch,auf,aus,ausser,ausserdem,außer,außerdem,b,bald,bei,beide,beiden,beim,beispiel,bekannt,bereits,besonders,besser,besten,bin,bis,bisher,bist,c,d,d.h,da,dabei,dadurch,dafür,dagegen,daher,dahin,dahinter,damals,damit,danach,daneben,dank,dann,daran,darauf,daraus,darf,darfst,darin,darum,darunter,darüber,das,dasein, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_german {
            get {
                return ResourceManager.GetString("stop_words_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ένα,έναν,ένας,αι,ακομα,ακομη,ακριβως,αληθεια,αληθινα,αλλα,αλλαχου,αλλες,αλλη,αλλην,αλλης,αλλιως,αλλιωτικα,αλλο,αλλοι,αλλοιως,αλλοιωτικα,αλλον,αλλος,αλλοτε,αλλου,αλλους,αλλων,αμα,αμεσα,αμεσως,αν,ανα,αναμεσα,αναμεταξυ,ανευ,αντι,αντιπερα,αντις,ανω,ανωτερω,αξαφνα,απ,απεναντι,απο,αποψε,από,αρα,αραγε,αργα,αργοτερο,αριστερα,αρκετα,αρχικα,ας,αυριο,αυτα,αυτες,αυτεσ,αυτη,αυτην,αυτης,αυτο,αυτοι,αυτον,αυτος,αυτοσ,αυτου,αυτους,αυτουσ,αυτων,αφοτου,αφου,αἱ,αἳ,αἵ,αὐτόσ,αὐτὸς,αὖ,α∆ιακοπα,βεβαια,βεβαιοτατα,γάρ,γα,γα^,γε,γι,γ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_greek {
            get {
                return ResourceManager.GetString("stop_words_greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,abbastanza,abbia,abbiamo,abbiano,abbiate,accidenti,ad,adesso,affinché,agl,agli,ahime,ahimè,ai,al,alcuna,alcuni,alcuno,all,alla,alle,allo,allora,altre,altri,altrimenti,altro,altrove,altrui,anche,ancora,anni,anno,ansa,anticipo,assai,attesa,attraverso,avanti,avemmo,avendo,avente,aver,avere,averlo,avesse,avessero,avessi,avessimo,aveste,avesti,avete,aveva,avevamo,avevano,avevate,avevi,avevo,avrai,avranno,avrebbe,avrebbero,avrei,avremmo,avremo,avreste,avresti,avrete,avrà,avrò,avuta,avute,avuti,avuto,basta,ben,b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_italian {
            get {
                return ResourceManager.GetString("stop_words_italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,actualmente,acuerdo,adelante,ademas,además,adrede,afirmó,agregó,ahi,ahora,ahí,al,algo,alguna,algunas,alguno,algunos,algún,alli,allí,alrededor,ambos,ampleamos,antano,antaño,ante,anterior,antes,apenas,aproximadamente,aquel,aquella,aquellas,aquello,aquellos,aqui,aquél,aquélla,aquéllas,aquéllos,aquí,arriba,arribaabajo,aseguró,asi,así,atras,aun,aunque,ayer,añadió,aún,b,bajo,bastante,bien,breve,buen,buena,buenas,bueno,buenos,c,cada,casi,cerca,cierta,ciertas,cierto,ciertos,cinco,claro,comentó,como,con,conmigo,co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stop_words_spanish {
            get {
                return ResourceManager.GetString("stop_words_spanish", resourceCulture);
            }
        }
    }
}
